# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 23:19
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrustType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='extra', max_length=50, verbose_name='extra')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MeatTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='meatTopping', max_length=50, verbose_name='meatToppings')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crustType', models.ManyToManyField(default='CrustType', to='quickstart.CrustType')),
                ('extra', models.ManyToManyField(default='Extra', to='quickstart.Extra')),
                ('meatToppings', models.ManyToManyField(default='MeatTopping', to='quickstart.MeatTopping')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crustType', models.ManyToManyField(default='CrustType', to='quickstart.CrustType')),
                ('extra', models.ManyToManyField(default='Extra', to='quickstart.Extra')),
                ('meatToppings', models.ManyToManyField(default='MeatTopping', to='quickstart.MeatTopping')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='size', max_length=50, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SauceTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='name')),
                ('PriceSmall', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('PriceMedium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('PriceLarge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('PriceXLarge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('meatToppings', models.ManyToManyField(default='MeatTopping', to='quickstart.MeatTopping')),
                ('sauceToppings', models.ManyToManyField(default='SauceToppings', to='quickstart.SauceTopping')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='status:', max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='VeggieTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='veggieTopping', max_length=50, verbose_name='veggieToppings')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='specialtypizza',
            name='veggieToppings',
            field=models.ManyToManyField(default='VeggieTopping', to='quickstart.VeggieTopping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauceToppings',
            field=models.ManyToManyField(default='SauceToppings', to='quickstart.SauceTopping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ManyToManyField(default='PizzaSize', to='quickstart.PizzaSize'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='veggieToppings',
            field=models.ManyToManyField(default='VeggieTopping', to='quickstart.VeggieTopping'),
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='sauceToppings',
            field=models.ManyToManyField(default='SauceToppings', to='quickstart.SauceTopping'),
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='size',
            field=models.ManyToManyField(default='PizzaSize', to='quickstart.PizzaSize'),
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='status',
            field=models.ManyToManyField(default='Status', to='quickstart.Status'),
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='veggieToppings',
            field=models.ManyToManyField(default='VeggieTopping', to='quickstart.VeggieTopping'),
        ),
    ]
