# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20170105_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedpizza',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
