# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20170117_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpizza',
            name='name',
            field=models.CharField(default='extra', max_length=50, verbose_name='extra'),
        ),
    ]
