# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_dietaryrestrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestrictionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dietary', max_length=50, verbose_name='dietary')),
            ],
        ),
        migrations.RemoveField(
            model_name='dietaryrestrictions',
            name='name',
        ),
        migrations.AddField(
            model_name='dietaryrestrictions',
            name='dietaryRestrictionsList',
            field=models.ManyToManyField(blank=True, default='DietList', to='quickstart.DietaryRestrictionsList'),
        ),
    ]
