# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20170130_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrestrictionslist',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='name'),
        ),
    ]
