# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_remove_dietaryrestrictions_veggietoppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrestrictions',
            name='dietaryRestrictionsList',
            field=models.ManyToManyField(blank=True, default='DietaryRestrictionsList', to='quickstart.DietaryRestrictionsList'),
        ),
    ]
