# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_auto_20170130_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrestrictionslist',
            name='meatToppings',
            field=models.ManyToManyField(blank=True, default='MeatTopping', to='quickstart.MeatTopping'),
        ),
        migrations.AddField(
            model_name='dietaryrestrictionslist',
            name='sauceToppings',
            field=models.ManyToManyField(default='SauceToppings', to='quickstart.SauceTopping'),
        ),
        migrations.AddField(
            model_name='dietaryrestrictionslist',
            name='veggieToppings',
            field=models.ManyToManyField(blank=True, default='VeggieTopping', to='quickstart.VeggieTopping'),
        ),
    ]
