# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20170207_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrestrictionslist',
            name='crustType',
            field=models.ManyToManyField(default='CrustType', to='quickstart.CrustType'),
        ),
        migrations.AlterField(
            model_name='dietaryrestrictionslist',
            name='sauceToppings',
            field=models.ManyToManyField(blank=True, default='SauceToppings', to='quickstart.SauceTopping'),
        ),
    ]
