# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_auto_20170207_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrestrictionslist',
            name='extra',
            field=models.ManyToManyField(blank=True, default='Extra', to='quickstart.Extra'),
        ),
    ]
